[[main]]
  identifier = "docs"
  name = "Docs"
  url = "docs"
  weight = 1

[[main]]
  identifier = "updates"
  name = "Updates"
  url = "updates"
  weight = 2

[[main]]
  identifier = "blog3"
  name = "Blog3"
  url = "blog3"
  weight = 3
  
[[main]]
  identifier = "blog4"
  name = "Blog4"
  url = "blog4"
  weight = 4
  
[[main]]
  identifier = "blog5"
  name = "Blog5"
  url = "blog5"
  weight = 5
  
[[main]]
  identifier = "blog6"
  name = "Blog6"
  url = "blog6"
  weight = 6
  
